# Generated by Django 2.1.5 on 2019-01-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190124_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rate',
        ),
    ]
