# Generated by Django 2.1.5 on 2019-01-25 10:00

import customer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190124_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dog-images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='reservations',
            field=models.IntegerField(default=0, validators=[customer.validators.min_validator]),
        ),
    ]
