# Generated by Django 2.1.5 on 2019-01-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190125_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='customer.Customer'),
        ),
    ]
