# Generated by Django 2.1.5 on 2019-01-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogitems',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_item', to='customer.Dog'),
        ),
        migrations.AlterField(
            model_name='dogitems',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_item', to='reservation.Reservation'),
        ),
    ]
