# Generated by Django 2.1.5 on 2019-01-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190125_1000'),
        ('reservation', '0003_auto_20190124_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='customer.Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('unclosed', 'unclosed'), ('pending', 'pending'), ('acepted', 'acepted'), ('concluded', 'concluded'), ('refused', 'refused'), ('canceled', 'canceled')], default='pending', max_length=9),
        ),
    ]
