# Generated by Django 2.1.5 on 2019-01-28 06:31

from django.db import migrations, models
import reservation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190125_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(validators=[reservation.validators.actual_date_validator]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.DurationField(validators=[reservation.validators.hour_validator]),
        ),
    ]
